swagger: '2.0'
info:
  description: API for user login
  version: 1.0.0
  title: User Login API
paths:
  /login:
    post:
      tags:
        - user
      summary: Login a user
      description: This endpoint allows a user to login by providing a username and password.
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: User object that needs to login
          required: true
          schema:
            type: object
            required:
              - username
              - password
            properties:
              username:
                type: string
              password:
                type: string
      responses:
        200:
          description: Login successful
          schema:
            type: object
            properties:
              message:
                type: string
                example: Login successful
              access_token:
                type: string
                example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
        400:
          description: Missing username or password
          schema:
            type: object
            properties:
              error:
                type: string
                example: Missing username or password
        401:
          description: Invalid username or password
          schema:
            type: object
            properties:
              error:
                type: string
                example: Invalid username or password